### ISSUE TITLE
Traceback Error.

### ISSUE THREAD

**Issue by adsad223s** [Tenpi/Defuzers#1]
C:\Users\Name>C:\Users\Edward\Downloads\defuzers-0.0.1-win-x64\defuzers\main.exe
Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.
                 It can be downloaded at https://aka.ms/vs/16/release/vc_redist.x64.exe
Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "routes\functions.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "torchvision\__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "torch\__init__.py", line 130, in <module>
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\Name\Downloads\defuzers-0.0.1-win-x64\defuzers\_internal\torch\lib\asmjit.dll" or one of its dependencies.
[14216] Failed to execute script 'main' due to unhandled exception!

I have Microsoft Visual C++ Installed

**Comment by Tenpi** [comment]
Can you try replacing the torch in `_internals/torch` with this one?

https://huggingface.co/defuzers/torch/blob/main/torch-cuda.zip
